extract:
  spect_params:
    ref: evsonganaly
  segment_params:
    threshold: 1500 # arbitrary units of amplitude
    min_syl_dur: 0.01 # ms
    min_silent_dur: 0.006 # ms

  todo_list:
    -
      bird_ID : gy6or6
      file_format: evtaf
      feature_group:
        - # fill this in as 'knn'
      data_dirs:
        - # this is the path to the training data on your computer

      output_dir: . # this will put the output in the same directory as the tutorial

      labelset: iabcdefghjk